import pathlib

CURRENT_DIRECTORY = pathlib.Path(__file__).parent
SHADER_DIRECTORY = CURRENT_DIRECTORY / "shaders"
BRANCH_VERTEX_SHADER_PATH = SHADER_DIRECTORY / "branch_vertex.glsl"
BRANCH_FRAGMENT_SHADER_PATH = SHADER_DIRECTORY / "branch_fragment.glsl"
SHADOW_VERTEX_SHADER_PATH = SHADER_DIRECTORY / "shadow_vertex.glsl"
SHADOW_FRAGMENT_SHADER_PATH = SHADER_DIRECTORY / "shadow_fragment.glsl"

RESOURCE_DIRECTORY = CURRENT_DIRECTORY.parent / "resources"
SCRIBBLE_TEXTURE_PATH = RESOURCE_DIRECTORY / "scribble.png"

TREE_X = 600
TREE_Y = 100
